---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: plugins/docker
  settings:
    force_tag: true
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick
    tags:
    - ${DRONE_COMMIT_SHA}
    - dev-${DRONE_BUILD_NUMBER}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    branch:
      exclude:
      - master
    event:
    - push

- name: trivy_scan
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/trivyscanner:master
  commands:
  - trivy --version
  - trivy image --ignore-unfixed --exit-code 0 --no-progress quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick:${DRONE_COMMIT_SHA}
  when:
    branch:
      exclude:
      - master
    event:
    - push

- name: build_master
  pull: if-not-exists
  image: plugins/docker
  settings:
    force_tag: true
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick
    tags:
    - b${DRONE_BUILD_NUMBER}
    - ${DRONE_REPO_BRANCH}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
    - push

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
